# Generated by Django 4.0.5 on 2022-06-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theChowkidarApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/user/profile/%Y/%m/%d/'),
        ),
    ]
