# Generated by Django 4.0.5 on 2022-06-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theChowkidarApp', '0003_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, unique=True)),
                ('otp', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
