# Generated by Django 4.0.5 on 2022-06-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theChowkidarApp', '0004_accountverify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountverify',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
    ]
