# Generated by Django 4.0.5 on 2022-06-08 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theChowkidarApp', '0006_user_otp_expair'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp_expair',
            new_name='otp_expire',
        ),
    ]
