# Generated by Django 4.0.5 on 2022-06-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theChowkidarApp', '0007_rename_otp_expair_user_otp_expire'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountVerify',
        ),
        migrations.AddField(
            model_name='user',
            name='is_created',
            field=models.BooleanField(default=False),
        ),
    ]
